spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SlipApp
    username: postgres
    password: Gerardo18
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jbdc:
          lob:
            non-contextual-creation: true
